[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
enableXsrfProtection = true
enableCORS = true

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true
