name: Keep Streamlit alive

on:
  schedule:
    - cron: "0 */10 * * *"   # kerran 10 tunnissa
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -sS --max-time 30 "https://henryagent.streamlit.app/?ping=1" || true
